# Generated by Django 3.1 on 2020-10-11 19:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_comment',
            new_name='BlogComment',
        ),
        migrations.RenameModel(
            old_name='blog_post',
            new_name='BlogPost',
        ),
    ]
